// HEADING,
// TITLE,
// SUB_TITLE,
// INPUT_LABEL & PALCEHOLDER
export const PRIMARY_COLOR = '#263238';
export const TEXT_COLOR_DEFAULT = PRIMARY_COLOR;
//TAG COLOR, BUTTON_TITLE
export const TEXT_COLOR_WHITE = '#FFFFFF';
export const TEXT_COLOR_INFO = '#2C98F0';
export const TEXT_COLOR_ERROR = '#F44336';
// PRODUCT_NAME
// CATEGORY_NAME
export const TEXT_COLOR_BLACK = '#000000';
// PRODUCT_DESCRIPTION
export const TEXT_COLOR_MEDIUM_BLACK = 'rgba(0, 0, 0, 0.84)';
// RATING_DESCRIPTION
// DRAWER_COMPONENTS
// MOSTLY_LONG_DESCRIPTION LIKE ORDER_DETAIL, ADDRESS_DESCRIPTION ETC
// REVIEWS_TEXT
export const TEXT_COLOR_LIGHT_BLACK = 'rgba(0, 0, 0, 0.54)';
export const TEXT_COLOR_TAB_ICON_TITLE = 'rgba(0, 0, 0, 0.5)';

export const BACKGROUND_COLOR_DEFAULT = '#FFFFFF';
export const BACKGROUND_COLOR_PRIMARY = '#673AB7';
export const BACKGROUND_COLOR_HASH_TAG = '#8DD455';
export const BACKGROUND_COLOR_RATING_START = '#FFC107';
export const BACKGROUND_COLOR_VERIFIED_REVIEW_ICON = '#1BB55C';
export const BACKGROUND_COLOR_PRICING_COMPONENT = '#3E1389';
export const BBACKGROUND_COLOR_TAG = '#3E1389';
export const BACKGROUND_COLOR_LIKE_ICON = '#061D28';
export const BACKGROUND_COLOR_SHARE_ICON = '#061D28';
export const BACKGROUND_COLOR_SAVE_ICON = '#323232';
export const BACKGROUND_COLOR_STAR_ICON = '#323232';
export const BACKGROUND_COLOR_TAB_ICON_FOCUSED = TEXT_COLOR_MEDIUM_BLACK;
export const BACKGROUND_COLOR_TAB_ICON = 'rgba(0, 0, 0, 0.5)';
export const BACKGROUND_COLOR_PROFILE_HEADER = 'rgba(103, 58, 183, 0.8)';

export const BACKGROUND_COLOR_SWITCH_TAIL_ON = '#2196F3';
export const BACKGROUND_COLOR_SWITCH_HEAD_ON = '#2C98F0';
export const BACKGROUND_COLOR_BADGES = '#EE0064';

export const BORDER_COLOR_HOME_SCREEN_TAB_ACTIVE = '#2C3BFE';
export const BORDER_COLOR_HOME_SCREEN_TAB_DEFAULT = '#BABABA';
export const CELEBRITY_CARD_TEXT_COLOR_DEFAULT = '#180F45';
export const BACKGROUND_COLOR_LOADING_SPINNER_DEFAULT = '#4F52FF';
export const BORDER_COLOR_DEFAULT = '#F3F3F3';
export const DRAWER_HIGHLIGHTED_ITEM_COLOR_DEFAULT = '#FB8823';
export const DRAWER_NOTIFICATIONS_COLOR_DEFAULT = '#F3F3F3';
export const ICON_TITLE_COLOR_DEFAULT = '#4F5157';
export const USER_PROFILE_TEXT_COLOR_DEFAULT = '#333333';
export const PENDING_REVIEWS_TEXT_COLOR_DEFAULT = '#070016';

export const BACKGROUND_BUTTON_PRIMARY = '#2C3BFE';
export const LINE_COLOR_DEFAULT = '#F3F3F3';
export const LINE_COLOR_VIDEO_REQUEST_SCREEN = '#F2F2F2';

// Video Request
export const VIDEO_REQUEST_DESCRIPTION_COLOR_DEFAULT = '#4F5157';
export const IN_PROGRESS_PENDING_APPROVAL_COLOR_DEFAULT = '#FB8823';
export const DECLINED_PENDING_PAYMENT_EXPIRED_COLOR_DEFAULT = '#EE0064';
export const COMPLETED_COLOR_DEFAULT = '#00AF66';
export const REQUEST_ACCEPTED_COLOR_DEFAULT = '#070016';

// Progress Bar
export const FILLED_PROGRESS_BAR = '#FFF';
export const UNFILLED_PROGRESS_BAR = 'rgba(255,250,250,.5)';

export const TEXT_INPUT_BORDER_COLOR = '#CCCCCC';

export const TEXT_INPUT_UNSELECT_COLOR = '#CCCCCC';
export const APPLY_DISCOUNT_TEXT_COLOR = '#D200CA';
export const PLACEHOLDER_TEXT_COLOR_DEFAULT = '#4F5157';

export const IMAGE_BORDER = '#F3F3F3';
//Local Colors
export const AVATAR_BORDER_F3F3F3 = '#F3F3F3';
export const ACTION_SHEET_BORDER_GAP_F0F0F0 = '#F0F0F0';
export const DELIVERED_BY_KEYKI_180F45 = '#180F45';
export const DISCOUNT_OFF_COLOR_FB8823 = '#FB8823';
export const SELECTED_SIZE_BOX_BACKGROUND_2C3BFE = '#2C3BFE';
export const RESPONSIVE_VIEW_BORDER_F3F3F3 = '#F3F3F3';
export const TOTAL_CONTAINER_BORDER_COLOR_CCC = '#ccc';
export const ALL_SELECT_BORDER_DDD = '#ddd';
export const TITLE_IN_CART_180F45 = '#180F45';
export const REMOVE_COLOR_EE0064 = '#EE0064';
export const ATTRIBUTES_VALUES_555 = '#555';
export const COUPAN_CONTAINER_BORDER_AND_BACKGROUND_BABABA = '#bababa';
export const CHECKOUT_TABS_TEXT_BDBDBD = '#BDBDBD';
export const MINIMUM_TINT_COLOR = '#2C3BFE';
export const MAXIMUM_TINT_COLOR = '#dcdcdc';
export const SLIDER_THUMB_STYLE_SELECTED_BORDER = '#2C3BFE';
export const SLIDER_THUMB_STYLE_UN_SELECTED_BORDER = '#4F5157';
export const CONTENT_LOADER_BACKGROUND = '#dde1ec';
export const CONTENT_LOADER_FOREGROUND = '#e9ebea';
export const ITEM_SEPARATOR_BORDER_COLOR_F3F3F3 = '#F3F3F3';
export const SEARCH_TAGS_BACKGROUND_COLOR_5E32BC = '#5E32BC';
export const ORDER_ITEM_BORDER_COLOR_F2F2F2 = '#F2F2F2';

//Secondary SplashScreen
export const GIF_1_2C3BFE = '#2C3BFE';
export const GIF_2_D200CA = '#D200CA';
export const GIF_3_EE0064 = '#EE0064';
export const PRIMARY_COLOR_P100 = '#2C3BFE';
export const Sale_ORANGE = '#FB8823';
export const GREEN_INDICATOR = '#00AF66';
export const SECONDARYM300 = '#EE0064';

export const KEYKI_BODY_TEXT_COLOR = '#180F45';
